### ISSUE TITLE
NaN validation loss when benchmarking

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#106]
The models `vesteinn/ScandiBERT` and `mideind/IceBERT-mC4-is` get NaN validation loss when benchmarking.

We need to check if this is due to the framework or the models themselves. If it's the models then an `InvalidBenchmark` should be thrown instead of getting ~0% scores on everything.

**Comment by saattrupdan** [comment]
This seems to be mixed precision causing this. When disabling `fp16` it stops occuring. We need to figure out what the solution is in this case. Either we would explicitly look for NaN validation loss, in which case it should restart the evaluation without `fp16`, or alternatively `fp16` should never be enabled by default, and instead by enabled if we're running out of memory.

@peterbjorgensen @AJDERS @KennethEnevoldsen Thoughts?

**Comment by saattrupdan** [comment]
@KennethEnevoldsen I would guess that we would be able to catch the NaN loss if it occurs early. Maybe one way could be having a check within the `compute_metrics` function, and throw an error if the val loss is NaN. The benchmarking script could catch that error and restart the benchmark with `fp16` set. 

But this assumes that these models all exhibit NaN loss in the first evaluation (step 30). I noticed that `xlm-roberta-base` also has weird behaviour now - I'd have to check if that's due to NaN loss too.

**Comment by KennethEnevoldsen** [comment]
Hmm right. if we do 32 as default, but switch to fp16 if there is insufficient memory though that would make it notably slower (apparently up to 8 times). I would probably just set a custom flag for the specific models and raise a warning if you try to call them with fp16.
