### ISSUE TITLE
Change NER output to structured generation

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#128]
Currently, for generative models, we ask the models to produce JSON dictionaries that contain all of the named entities within the text. The keys in the dictionaries are things like "person" and "location" (translated to the given language), with values being lists of strings, being the entities in the text of that type. An example:

```json
{"person": ["Peter"], "location": [], "organization": [], "miscellaneous": ["Adidas"]}
```

Rather than asking the model to produce this JSON dict as-is, we can instead use _structured generation_, where the JSON structure and keys are fixed, and the model only needs to output the contents of the lists. This means that we're not penalising the models for not knowing the proper JSON format, which we can test separately, if needed. Aside from that, the models also have to generate fewer tokens, speeding up generation.

**Comment by timpal0l** [comment]
This is great! I noticed when running the SUC3.0 it complains alot about the json not being formatted correctly. Which makes the comparision much harder for generative models.
```bash
2024-01-10 11:55:07 ⋅ The model output is not valid JSON, so cannot parse it. Skipping. Here is the output:
```
```bash 
'{"person": [""], "", "plats": [], "organisation": ["Häst"], "diverse": []}'
```

**Comment by saattrupdan** [comment]
Seems like this library could be useful to achieve this - it seems to support vLLM models too:

https://github.com/outlines-dev/outlines

**Comment by saattrupdan** [comment]
The `lm-format-enforcer` seems to integrate easier with vLLM, and it's more minimal.
