### ISSUE TITLE
[MODEL EVALUATION REQUEST] Small QWEN-1.5 models

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#212]
**Describe the model**
The new QWEN-1.5 series is a collection of multilingual decoder models from Alibaba. They've released both base models and tuned models, in many different sizes. This issue concerns the ones of size up to and including 4B. They're all available in [this Hugging Face collection](https://huggingface.co/collections/Qwen/qwen15-65c0a2f577b1ecb76d786524). They're multilingual and should thus be evaluated on all models.

- [x] Qwen/Qwen1.5-0.5B
- [x] Qwen/Qwen1.5-0.5B-Chat
- [x] Qwen/Qwen1.5-1.8B
- [x] Qwen/Qwen1.5-1.8B-Chat
- [x] Qwen/Qwen1.5-4B
- [x] Qwen/Qwen1.5-4B-Chat

**Comment by saattrupdan** [comment]
Bug! https://github.com/ScandEval/ScandEval/issues/264

**Comment by peter-sk** [comment]
I am doing the first except for NER tasks.

**Comment by saattrupdan** [comment]
I'm evaluating this on the NER tasks.
