### ISSUE TITLE
[MODEL EVALUATION REQUEST] bineric/NorskGPT-Llama-13B-v0.1

### ISSUE THREAD

**Issue by buzzCraft** [ScandEval/ScandEval#221]
### 📊 Describe the model

This is the 13b llama version of NorskGPT. I expect it to score lower than the Mistral one, but it should end up being the best Llama based. It would be interesting to see the eval, as both of the NorskGPT models are trained for the same number of epochs, on the same datasets.

https://huggingface.co/bineric/NorskGPT-Llama-13B-v0.1

**Comment by saattrupdan** [comment]
Done, added to leaderboards now - best Llama-2-13b model on the Norwegian leaderboard, but a fair amount worse than the NorskGPT based on Mistral-7b-v0.1 though, as you predicted.

https://scandeval.com/norwegian-nlg/
