### ISSUE TITLE
[BENCHMARK DATASET REQUEST] Swedish Scholastic Aptitude Test Synonyms (SweSAT)

### ISSUE THREAD

**Issue by timpal0l** [ScandEval/ScandEval#233]
### Dataset name

Swedish Scholastic Aptitude Test Synonyms (SweSAT)

### Dataset link

https://spraakbanken.gu.se/resurser/swesat-synonyms

### Dataset languages

- [ ] Danish
- [X] Swedish
- [ ] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [ ] Dutch
- [ ] English

### Describe the dataset

The dataset provides a gold standard for Swedish word synonymy/definition. The test items are collected from the Swedish Scholastic Aptitude Test (högskoleprovet), currently spanning the years 2006--2021 and 822 vocabulary test items. The task for the tested system is to determine which synonym or definition of five alternatives is correct for each test item.

This dataset is a subset of SuperLim2, more information can be found here: https://spraakbanken.gu.se/resurser/superlim

Possible implementation; https://github.com/timpal0l/superlim-word-level-eval/blob/main/app/swesat_gpt.py (which is stolen from here https://github.com/Muennighoff/sgpt?tab=readme-ov-file#cross-encoder)

*Youtube talk* - https://www.youtube.com/watch?v=ESx22ZNXydo&t=1959s

**Comment by saattrupdan** [comment]
Closing this in favour of #257.
