### ISSUE TITLE
Evaluate >7B models on Danish knowledge datasets

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#252]
Since we added the new Danish knowledge datasets Danske Talemåder and Danish Citizen Tests, we need to evaluate existing leaderboard models on these. This has been done for 7B models and below, but the larger models are still pending.

These can be benchmarked with the command `scandeval -t knowledge -l da -m <model-id>`.

- [x] AI-Sweden-Models/gpt-sw3-20b
- [x] RuterNorway/Llama-2-13b-chat-norwegian

**Comment by RJuro** [comment]
`{"dataset": "danske-talemaader", "task": "knowledge", "dataset_languages": ["da"], "model": "RuterNorway/Llama-2-13b-chat-norwegian", "results": {"raw": {"test": [{"mcc": 0.49376171362844307, "accuracy": 0.609375}, {"mcc": 0.530658410808551, "accuracy": 0.6435546875}, {"mcc": 0.5202494153281539, "accuracy": 0.6357421875}, {"mcc": 0.4941781560303097, "accuracy": 0.6123046875}, {"mcc": 0.542227260657451, "accuracy": 0.6533203125}, {"mcc": 0.5452598950588033, "accuracy": 0.65234375}, {"mcc": 0.5570570787855551, "accuracy": 0.66015625}, {"mcc": 0.5375672609484189, "accuracy": 0.64453125}, {"mcc": 0.5179127276589511, "accuracy": 0.6279296875}, {"mcc": 0.5548251064877349, "accuracy": 0.6650390625}]}, "total": {"test_mcc": 52.93697025392372, "test_mcc_se": 1.4045997937819554, "test_accuracy": 64.04296875, "test_accuracy_se": 1.1801833372058776}}, "num_model_parameters": -1, "max_sequence_length": 4096, "vocabulary_size": 32000, "generative": true, "few_shot": true, "validation_split": false, "scandeval_version": "11.0.0"}
{"dataset": "danish-citizen-tests", "task": "knowledge", "dataset_languages": ["da"], "model": "RuterNorway/Llama-2-13b-chat-norwegian", "results": {"raw": {"test": [{"mcc": 0.44586193164719984, "accuracy": 0.62109375}, {"mcc": 0.41191713925580103, "accuracy": 0.595703125}, {"mcc": 0.3871968244973592, "accuracy": 0.5859375}, {"mcc": 0.4025160334356795, "accuracy": 0.591796875}, {"mcc": 0.3841425195759475, "accuracy": 0.583984375}, {"mcc": 0.427162872457086, "accuracy": 0.6015625}, {"mcc": 0.45800340168661363, "accuracy": 0.626953125}, {"mcc": 0.4172960107783416, "accuracy": 0.591796875}, {"mcc": 0.4157417345116005, "accuracy": 0.59765625}, {"mcc": 0.415196768230159, "accuracy": 0.595703125}]}, "total": {"test_mcc": 41.65035236075788, "test_mcc_se": 1.4348806001370995, "test_accuracy": 59.921875, "test_accuracy_se": 0.8762978655792503}}, "num_model_parameters": -1, "max_sequence_length": 4096, "vocabulary_size": 32000, "generative": true, "few_shot": true, "validation_split": false, "scandeval_version": "11.0.0"}`
