### ISSUE TITLE
[BUG] ray.exceptions.GetTimeoutError when providing multiple languages as input

### ISSUE THREAD

**Issue by evigog** [ScandEval/ScandEval#283]
### 🐛 Describe the bug

I get a time-out error from ray ( ../ray/_private/worker.py, line 819, ray.exceptions.GetTimeoutError: Get timed out: some object(s) not ready) when calling the benchmark function as shown below:

`benchmark(model="AI-Sweden-Models/gpt-sw3-20b-instruct", task="linguistic-acceptability", language=en,is,no)`

I am running the code on two A100 GPUs 40GB each. The time-out appears after the evaluation is completed for at least one language.

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

11.0.0

**Comment by saattrupdan** [comment]
Seems like this might be related to this vLLM issue: https://github.com/vllm-project/vllm/issues/1058
