### ISSUE TITLE
Add multi-GPU support for finetuning

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#37]
Currently, when using multiple GPUs, the progress bars are not moving and it doesn't seem like anything is happening, despite the fact that the GPUs _are_ in use. If they're indeed benchmarking the models then this progress should be displayed.

**Comment by KennethEnevoldsen** [comment]
Does this mean that using multiple GPUs does indeed work, simply that the progress bar is not showing as intended? (in which case the title might be misleading)

**Comment by saattrupdan** [comment]
Yes, multiple GPUs do work, but the command-line output is simply stuck at "Finetuning model: 0it [00:00, ?it/s]".

**Comment by saattrupdan** [comment]
Closing for now, since the crucial point is using multi-GPUs for large decoder models, and vLLM supports that - this has been added in https://github.com/ScandEval/ScandEval/releases/tag/v12.0.0.
