### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by farup** [ScandEval/ScandEval#377]
Hi, 

First, thanks for the good work!

I have some questions regarding test results; in the output file (scandeval_benchmark_results.jsonl) I am getting total test scores such as “test_mcc” and “test_mcc_se”. What is the “_se” on these results?

I am also getting mcc scores outside of the interval [-1, 1] together with BertScores above 1. Do you have any idea of why? 

I am testing pretrained (on norwegian datasets) GPT2 models.
scandeval_version: "12.3.2"

**Comment by saattrupdan** [comment]
Hi, and thanks!

The "_se" stands for standard error, and is used to create the 95% confidence intervals on the leaderboards (https://scandeval.com/).

MCC scores outside [-1, 1] isn't really possible, but if we're talking the scores in the "total" key of the results dictionary then this is between [-100, 100], as this is what is being used on the leaderboards. Same with BERTScores.

Hope that helps! If not, then please re-open the issue :)
