### ISSUE TITLE
[MODEL EVALUATION REQUEST] German Wikipedia LMs (GWLMs) - TEAMS

### ISSUE THREAD

**Issue by stefan-it** [ScandEval/ScandEval#404]
### Model ID

gwlms/teams-base-dewiki-v1-discriminator

### Model type

Encoder model (e.g., BERT)

### Model languages

- [ ] Danish
- [ ] Swedish
- [ ] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [X] German
- [ ] Dutch
- [ ] English

### Merged model

Not a merged model

**Comment by stefan-it** [comment]
I've pretrained this TEAMS ([Training ELECTRA Augmented with Multi-word Selection](https://arxiv.org/abs/2106.00139)) model on a recent German Wikipedia Dump and I am very curious to see the results :)

**Comment by saattrupdan** [comment]
@stefan-it  Sure thing! I created a bunch of PRs on your model repos, to convert them to safetensors (this is mainly to get a correct parameter count). When they're merged in I'll start the evaluations :)

**Comment by stefan-it** [comment]
Many thanks @saattrupdan ! I merged them now :)

**Comment by saattrupdan** [comment]
@stefan-it  Great! It's in the queue now, so should be live on Monday 🙂

**Comment by saattrupdan** [comment]
@stefan-it And they're live! I benchmarked the following:

> gwlms/deberta-base-dewiki-v1, gwlms/teams-base-dewiki-v1-discriminator, gwlms/bert-base-dewiki-v1

These can now be found on the [German leaderboard](https://scandeval.com/german-nlu/).
