### ISSUE TITLE
[BENCHMARK DATASET REQUEST] dutch-cola

### ISSUE THREAD

**Issue by BramVanroy** [ScandEval/ScandEval#419]
### Dataset name

GroNLP/dutch-cola

### Dataset link

https://huggingface.co/datasets/GroNLP/dutch-cola

### Dataset languages

- [ ] Danish
- [ ] Swedish
- [ ] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [X] Dutch
- [ ] English

### Describe the dataset

Dutch CoLA is a corpus of linguistic acceptability for Dutch: a dataset consisting of sentences in Dutch, each marked as either acceptable (class 1) or unacceptable (class 0). These sentences are collected from existing descriptions of Dutch grammar (see sources below) with expert-annotated acceptability labels.

I might add it through a PR when I find the time.

**Comment by saattrupdan** [comment]
Included in https://github.com/ScandEval/ScandEval/pull/503.
