### ISSUE TITLE
[MODEL EVALUATION REQUEST] Llama-3-8B-instruct-dansk

### ISSUE THREAD

**Issue by emillykkejensen** [ScandEval/ScandEval#426]
### Model ID

emillykkejensen/Llama-3-8B-instruct-dansk

### Model type

Decoder model (e.g., GPT)

### Model languages

- [X] Danish
- [ ] Swedish
- [ ] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [ ] Dutch
- [ ] English

### Merged model

Not a merged model

**Comment by saattrupdan** [comment]
It's live now! https://scandeval.com/danish-nlg/
