### ISSUE TITLE
[MODEL EVALUATION REQUEST] Phi-3-mini-4k-instruct-dansk

### ISSUE THREAD

**Issue by emillykkejensen** [ScandEval/ScandEval#427]
### Model ID

emillykkejensen/Phi-3-mini-4k-instruct-dansk

### Model type

Decoder model (e.g., GPT)

### Model languages

- [X] Danish
- [x] Swedish
- [x] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [ ] Dutch
- [ ] English

### Merged model

Not a merged model

**Comment by saattrupdan** [comment]
This requires Phi3 to be supported in vLLM. [This vLLM PR](https://github.com/vllm-project/vllm/pull/4298) merged that functionality into main, so waiting for the next release to benchmark it.

**Comment by saattrupdan** [comment]
Live now!

https://scandeval.com/danish-nlg/
