### ISSUE TITLE
[MODEL EVALUATION REQUEST] Boreas-7B-chat

### ISSUE THREAD

**Issue by yhavinga** [ScandEval/ScandEval#428]
### Model ID

https://huggingface.co/yhavinga/Boreas-7B-chat

### Model type

Decoder model (e.g., GPT)

### Model languages

- [ ] Danish
- [ ] Swedish
- [ ] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [X] Dutch
- [X] English

### Merged model

Not a merged model

**Comment by saattrupdan** [comment]
It's live now! https://scandeval.com/dutch-nlg/

**Comment by yhavinga** [comment]
Many thanks!
