### ISSUE TITLE
[BUG] <Incredibly low SUC3.0 results in Swedish and omitting SweDN benchmark >

### ISSUE THREAD

**Issue by Knobi333** [ScandEval/ScandEval#441]
### 🐛 Describe the bug

Hello, I am currently using the ScandEval Python package and evaluating language models with the Swedish benchmarks. Two problems that I have encountered with all models I have evaluated is that the SweDN summarization benchmark is not is not evalueted and that the SUC3 Swedish named entity recognition benchmark results in incredibly low scores. 

The sweDN benchmark causes errors and the program just continues without benchmarking it when I run all of the benchmarks.

At first I thought that my models were just performing poorly, but when I tried to evaluate Nexusflow/Starling-LM-7B-beta, a model on the leading board, the SUC3 results where much lower than what was showcased. 

This is a part of the json file whit the SUC3 results: 

{"dataset": "suc3", "task": "named-entity-recognition", "dataset_languages": ["sv"], "model": "Nexusflow/Starling-LM-7B-beta", "results": {"raw": {"test": [{"micro_f1_no_misc": 0.009271523178807946, "micro_f1": 0.009034443817052512}, {"micro_f1_no_misc": 0.0, "micro_f1": 0.0}, {"micro_f1_no_misc": 0.0, "micro_f1": 0.0}, {"micro_f1_no_misc": 0.005034612964128383, "micro_f1": 0.003342618384401114}, {"micro_f1_no_misc": 0.0023823704586063135, "micro_f1": 0.00421274354923644}, {"micro_f1_no_misc": 0.0012040939193257074, "micro_f1": 0.0020790020790020787}, {"micro_f1_no_misc": 0.0, "micro_f1": 0.0}, {"micro_f1_no_misc": 0.0, "micro_f1": 0.0012422360248447203}, {"micro_f1_no_misc": 0.0, "micro_f1": 0.0}, {"micro_f1_no_misc": 0.0, "micro_f1": 0.0}]}, "total": {"test_micro_f1_no_misc": 0.17892600520868351, "test_micro_f1_no_misc_se": 0.1920616497705751, "test_micro_f1": 0.19911043854536864, "test_micro_f1_se": 0.1810121449632436}}, "num_model_parameters": 7241748480, "max_sequence_length": 8192, "vocabulary_size": 32002, "generative": true, "few_shot": true, "validation_split": false, "scandeval_version": "12.10.0"}

### Operating System

Windows

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

12.10.0

**Comment by saattrupdan** [comment]
Thanks for the bug report! This has recently occurred for Norwegian NER as well, so I suspect something happened in a recent release. I'm on it. 

As for the SweDN bug, can you post a separate issue with the traceback?

**Comment by saattrupdan** [comment]
@Knobi333 This should now be fixed in [v12.10.1](https://github.com/ScandEval/ScandEval/releases/tag/v12.10.1). Basically, it's due to having an old version of `outlines`, and currently vLLM doesn't allow a newer version of `outlines` (this will be fixed when [this vLLM PR](https://github.com/vllm-project/vllm/pull/4109) is merged and released). Thus, simply running `pip install -U outlines` should fix the issue. The new ScandEval version checks whether `outlines` has the correct version, and throws an error with update instructions.

If your error persists, then feel free to re-open this issue 🙂

**Comment by Knobi333** [comment]
Thank you! I did as you suggested and SUC3 works now! I created a new issue for the sweDN benchmark!
