### ISSUE TITLE
[BUG] <Error with SweDN benchmark>

### ISSUE THREAD

**Issue by Knobi333** [ScandEval/ScandEval#442]
### 🐛 Describe the bug

Hi, I have encountered a problem when trying to use the Swedish sweDN summarization benchmark. This is the error message I have received: 

2024-05-28 16:35:13 ⋅ Benchmarking Nexusflow/Starling-LM-7B-beta on the truncated version of the Swedish summarisation dataset SweDN
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████| 7.95k/7.95k [00:00<00:00, 34.0MB/s]
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████| 6.27k/6.27k [00:00<00:00, 26.8MB/s]
2024-05-28 16:35:17 ⋅ Loading model and tokenizer...
2024-05-28 16:35:32 ⋅ The model has 7,241,748,480 parameters, a vocabulary size of 32,002, and a maximum sequence length of 8,192.
Preprocessing data splits: 100%|██████████████████████████████████████████████████████████████████████████| 12/12 [04:09<00:00, 20.75s/it]
Benchmarking:   0%|                                                                                                | 0/10 [18:38<?, ?it/s]
2024-05-28 16:58:24 ⋅ Nexusflow/Starling-LM-7B-beta could not be benchmarked on the truncated version of the Swedish summarisation dataset SweDN. Skipping. The error message raised was 'NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":844, please report a bug to PyTorch. '

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

12.10.1

**Comment by saattrupdan** [comment]
It seems like this is a very cryptic OOM error, as per [this issue](https://github.com/pytorch/pytorch/issues/112377).

What's the output of `nvidia-smi` for you?

**Comment by Knobi333** [comment]
Do you mean this? 
---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 80GB HBM3          On  | 00000000:DF:00.0 Off |                   On |
| N/A   38C    P0             117W / 700W |                  N/A |     N/A      Default |
|                                         |                      |              Enabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| MIG devices:                                                                          |
+------------------+--------------------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |                   Memory-Usage |        Vol|      Shared           |
|      ID  ID  Dev |                     BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |
|                  |                                |        ECC|                       |
|==================+================================+===========+=======================|
|  0    6   0   0  |              12MiB / 20096MiB  | 26      0 |  1   0    1    0    1 |
|                  |               0MiB / 32767MiB  |           |                       |
+------------------+--------------------------------+-----------+-----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by saattrupdan** [comment]
What version of torch do you use?

Could you try reinstalling torch and trying again?

**Comment by Knobi333** [comment]
I am using the version 2.3.0. Will do!

**Comment by Knobi333** [comment]
I reinstalled my torch to version: Version: 2.3.0+cu121, but it did not work. However, my cuda version is 12.3, but pytorch only seems to be compatible up to 12.1.

**Comment by saattrupdan** [comment]
Hm alright. Doubt that it's to do with your CUDA version. This is a [known PyTorch issue](https://github.com/pytorch/pytorch/issues/122068), but it doesn't seem like there's a fix yet. The comments in the previous issue I linked to seems to indicate that it's related to the MIG GPU architecture, which your GPU also seems to be. 

Grasping at straws here: can you try to downgrade your torch and/or transformers and try again? That seems to have fixed the issue for a few people.

**Comment by Knobi333** [comment]
To what version can I downgrade them? It seems that the Scandeval version12.10.1 requires the torch version 2.3.0.

**Comment by Knobi333** [comment]
Previously, I was using the 4.40.0 version of transformers, which is also the lowest required version for Scandeval...

**Comment by saattrupdan** [comment]
Closing now, as this seems to be a hardware-specific issue, rather than an issue with the ScandEval package. If you don't think that's a fair assessment, then feel free to re-open!
