### ISSUE TITLE
[MODEL EVALUATION REQUEST] four-two-labs/lynx-micro

### ISSUE THREAD

**Issue by ali-mosavian** [ScandEval/ScandEval#447]
### Model ID

four-two-labs/lynx-micro

### Model type

Decoder model (e.g., GPT)

### Model languages

- [ ] Danish
- [X] Swedish
- [ ] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [ ] Dutch
- [ ] English

### Merged model

Not a merged model

**Comment by saattrupdan** [comment]
@ali-mosavian You had already benchmarked this model, right? If so, please leave the JSONL file here in the comments (you can wrap it in ``` tags for reading ease).

**Comment by ali-mosavian** [comment]
Thanks! =)
