### ISSUE TITLE
[BUG] circular dependency - `outlines>=0.0.37`

### ISSUE THREAD

**Issue by farup** [ScandEval/ScandEval#457]
### 🐛 Describe the bug

Hi, 

while running an evaluation as follows I'm encountering  dependencies issues:  

`benchmarker = Benchmarker()`
`
benchmarker(model=model_id, force=True)
`

`
scandeval 12.10.4 requires torch<3.0.0,>=2.3.0, but you have torch 2.1.2 which is incompatible.
vllm-flash-attn 2.5.8.post2 requires torch==2.3.0, but you have torch 2.1.2 which is incompatible.
`

>> pip install torch==2.3.0

`
xformers 0.0.23.post1 requires torch==2.1.2, but you have torch 2.3.0 which is incompatible.
vllm 0.3.3 requires torch==2.1.2, but you have torch 2.3.0 which is incompatible.
ai2-olmo 0.2.5 requires torch<2.3,>=2.0, but you have torch 2.3.0 which is incompatible.
`

>> pip install vllm -U

Then running the program gives message "Evaluating models on the named entity recognition task requires `outlines>=0.0.37`. Please upgrade this with `pip install -U outlines` and try again. This is a temporary measure and will be installed properly in the next release.'"

>> pip install outlnes==0.0.37

`
vllm 0.4.3 requires outlines==0.0.34, but you have outlines 0.0.37 which is incompatible.
`

Then down grading vllm till  0.4.2,  or lower which requires outlines < 0.0.37, and running into the same "task requires `outlines>=0.0.37`."

### Operating System

Linux

### Device

CUDA GPU

### Python version

3.10.x

### ScandEval version

12.10.4

**Comment by saattrupdan** [comment]
If you run `pip install scandeval[generative] && pip install -U outlines`, does that fix your issue?

The `outlines` bit is a known bug with vLLM and will get fixed in the next vLLM release (see [this issue](https://github.com/ScandEval/ScandEval/issues/414) for more details).

**Comment by farup** [comment]
`
pip install scandeval[generative] && pip install -U outlines
`
Throws  
`
vllm 0.4.2 requires outlines==0.0.34, but you have outlines 0.0.43 which is incompatible.
`
Alright, understood. Which version of vllm are you using?

**Comment by saattrupdan** [comment]
> `pip install scandeval[generative] && pip install -U outlines` Throws `vllm 0.4.2 requires outlines==0.0.34, but you have outlines 0.0.43 which is incompatible.` Alright, understood. Which version of vllm are you using?

I'm aware that the dependencies are in conflict with each other, but on all the machines we've tested (MacOS and Ubuntu), pip allows installing incompatible dependencies (whereas poetry does not, for instance). Could you let me know what version of pip that you're using?

As for your question, I'm using the newest vLLM (0.4.3).

**Comment by farup** [comment]
Somehow seems to work now with outlines 0.0.43, and vllm 0.4.3.

my pip version was 23.3.1.

Thanks for help!

**Comment by saattrupdan** [comment]
Perfect! Feel free to reopen if it comes back 🙂
