### ISSUE TITLE
[FEATURE REQUEST] Support llama.cpp backend

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#489]
### 🚀 The feature, motivation and pitch

Using the llama.cpp backend (via the Python bindings) will enable us to benchmark gguf models, and also make it easier to benchmark larger models with less VRAM available. 

### Additional context

Since the gguf models are saved in separate model repos, there’s full transparency in case the fp16 model is significantly better, say.

**Comment by Mikeriess** [comment]
Just adding my two cents: 

It seems it varies a little how people publish the gguf's. NorwAI put them in the same repo, and one then has to download the file manually, or use hf-hub and exclude everything else. Others have a branch for them, which makes it easy when loading from transformers (same repo, but with revision/branch x in the destination).

Is there an easy way to cover both scenarios? 😄

**Comment by saattrupdan** [comment]
> It seems it varies a little how people publish the gguf's. NorwAI put them in the same repo, and one then has to download the file manually, or use hf-hub and exclude everything else. Others have a branch for them, which makes it easy when loading from transformers (same repo, but with revision/branch x in the destination).
> Is there an easy way to cover both scenarios? 😄

ScandEval supports loading revisions of models, so in case the ggufs are in a separate branch then one could simply evaluate <model-id>@<branch-name>. If they're in the same repo then I assume that llama.cpp looks for gguf files in the repo, but I'm not sure about this. In any case, it sounds doable!
