### ISSUE TITLE
[BENCHMARK DATASET REQUEST] Belebele

### ISSUE THREAD

**Issue by Rijgersberg** [ScandEval/ScandEval#501]
### Dataset name

Belebele

### Dataset link

https://huggingface.co/datasets/facebook/belebele

### Dataset languages

- [X] Danish
- [X] Swedish
- [X] Norwegian (Bokmål or Nynorsk)
- [X] Icelandic
- [ ] Faroese
- [X] German
- [X] Dutch
- [X] English

### Describe the dataset

# The Belebele Benchmark: a Parallel Reading Comprehension Dataset in 122 Language Variants

> We present Belebele, a multiple-choice machine reading comprehension (MRC) dataset spanning 122 language variants. Significantly expanding the language coverage of natural language understanding (NLU) benchmarks, this dataset enables the evaluation of text models in high-, medium-, and low-resource languages. Each question is based on a short passage from the Flores-200 dataset and has four multiple-choice answers. The questions were carefully curated to discriminate between models with different levels of general language comprehension. The English dataset on its own proves difficult enough to challenge state-of-the-art language models. Being fully parallel, this dataset enables direct comparison of model performance across all languages. We use this dataset to evaluate the capabilities of multilingual masked language models (MLMs) and large language models (LLMs). We present extensive results and find that despite significant cross-lingual transfer in English-centric LLMs, much smaller MLMs pretrained on balanced multilingual data still understand far more languages. We also observe that larger vocabulary size and conscious vocabulary construction correlate with better performance on low-resource languages. Overall, Belebele opens up new avenues for evaluating and analyzing the multilingual capabilities of NLP systems.

https://arxiv.org/abs/2308.16884

This being a popular dataset, you may have already considered this dataset before and rejected it. However, I couldn't find any mention of it on your Github page, so I thought I would request it anyway.

## What is it measuring?
Machine reading comprehension using multiple choice questions.

## Why is it important to include it as a benchmark dataset in ScandEval?
- It measures reading comprehension
- Although the original texts are in English, all translations have been performed by humans, not models. I took a look at the Dutch portion of the data and although some of the subjects are not really European-focussed, the quality of the translations looks to be quite good.

## Number of datapoints
There are 900 rows per language. I don't know if you have guidelines, but it's problably not enough to train and evaluate an encoder-only model on. For few-shot evaluation of generative models it might be enough though.

## Reformat to extractive question answering
It might be possible to [repurpose the dataset into an extractive question answering dataset](https://arxiv.org/abs/2404.17342). However, in that paper more than half of the rows were lost in the process.

## Miscellaneous
- It is already part of the [Occiglot Euro Leaderboard](https://huggingface.co/spaces/occiglot/euro-llm-leaderboard).
- This could potentially be a contribution from the GPT-NL team. One caveat though: we have funding to work on benchmarks for _generative models_. If a benchmark can be trivially converted into a benchmark for encoder models we won't shy away from that, but we can't spend significant resources on it.

**Comment by saattrupdan** [comment]
Thanks for the suggestion!

It would be a great addition to the benchmark. As you said, it doesn't quite fit into the existing reading comprehension task, but we could create a separate multiple choice reading comprehension task, which just evaluates like MMLU/ARC/HellaSwag. This also excludes encoder models to be evaluated on it.

I've added this dataset in [this PR](https://github.com/ScandEval/ScandEval/pull/502).

It is quite small, as you said, so the current splits has been chosen as with the Icelandic Winogrande dataset: A train split of 64 samples, validation split with 128, and the rest being the test split.
