### ISSUE TITLE
[FEATURE REQUEST] Support for peft and adapters 

### ISSUE THREAD

**Issue by jekunz** [ScandEval/ScandEval#519]
### 🚀 The feature, motivation and pitch

The peft (https://huggingface.co/docs/peft) and adapters (https://huggingface.co/docs/hub/adapters) libraries are add-ons for transformers and popular for adapting LLMs with various PEFT methods. It would be convenient if there was support for evaluating peft models and/or adapter models in ScandEval.

**Comment by saattrupdan** [comment]
@jekunz I've made an initial attempt at implementing the LoRA support. Can you please test if it works with one of your adapter models?

Installation:
```
pip uninstall -y scandeval && pip install scandeval[generative]@git+https://github.com/ScandEval/ScandEval@feat/519-support-adapters && pip install peft
```

You run the model as usual. Here's what I tested against:
```
scandeval -m grimjim/Llama-3-Instruct-abliteration-LoRA-8B
```
