### ISSUE TITLE
Is ai Swedens non-commercial?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [ScandEval/ScandEval#544]
Hi it seems like ai-swedens model is marked as non-commercial, while llama is marked as commercial despite them using the same license. It might be that it is the versioning of the license that makes the difference, but it isn't entirely clear

**Comment by saattrupdan** [comment]
AI Sweden's base models _are_ marked as commercially viable, exactly for the reason you mention. The instruction tuned models are not, as they are finetuned on finetuning data generated by OpenAI models. So same reasoning as most of the other models marked as non-commercial on the leaderboards.

**Comment by KennethEnevoldsen** [comment]
Thanks that was exactly what I was looking to understand. Should we write somewhere about how this is determined?

**Comment by saattrupdan** [comment]
That'd make sense yeah. Where do you think makes sense? An FAQ on scandeval.com maybe?

**Comment by KennethEnevoldsen** [comment]
Let us start it as an FAQ and reorder it if needed. I could imagine it looking like this

> # FAQ
>
> ## How do you determine if a model is "Commercial" or not? 
> We generally determine this based on whether a model's license allows commercial use of the model. 
> However if we are aware that a model is trained on data, that does not allow for commercial use, we will set it non-commercial model, despite the stated license.
> 
> ## Not finding the answer that you are looking for?
> If don't find the answer that you are looking for feel free to ask your question in the [forum](https://github.com/ScandEval/ScandEval/discussions).

Then I would probably at least put a reference below the tables (so that people can find it).

Not sure I would make it a tab though.

**Comment by saattrupdan** [comment]
Do you mean to that section on the front page?

**Comment by KennethEnevoldsen** [comment]
Not sure what you are referring to - is there already a FAQ?

**Comment by saattrupdan** [comment]
Oh, I meant "Do you mean to add that section (that you wrote above) to the front page?"

**Comment by saattrupdan** [comment]
The front page is simply [this HTML file](https://github.com/ScandEval/scandeval.github.io/blob/main/index.md) - feel free to change it in a PR if that's what you meant 🙂

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Any news on this, regarding future plan? Otherwise I'll close this issue to avoid stale issues.

**Comment by KennethEnevoldsen** [comment]
Added a PR

**Comment by saattrupdan** [comment]
Up live now on https://scandeval.com.
