### ISSUE TITLE
[BENCHMARK DATASET REQUEST] schibsted-article-summaries

### ISSUE THREAD

**Issue by Mikeriess** [ScandEval/ScandEval#594]
### Dataset name

schibsted-article-summaries

### Dataset link

https://huggingface.co/datasets/Schibsted/schibsted-article-summaries

### Dataset languages

- [ ] Danish
- [X] Swedish
- [X] Norwegian (Bokmål or Nynorsk)
- [ ] Icelandic
- [ ] Faroese
- [ ] German
- [ ] Dutch
- [ ] English

### Describe the dataset

> Consist of published article summaries from Schibsted Medias Norwegian and Swedish newsrooms.

Schibsted just released this under cc-by-nc-nd-4.0, so I gues it is 100% unproblematic to include the norwegian and swedish subsets in ScandEval, in their respective leaderboards. I assume NORBERT (https://github.com/ltgoslo/NorBERT) would be suitable to calculate BERTScore in this case (assuming same evaluation method as Nordjylland News).

Schibsted also released the following datasets: 
- Front titles of VG (equivalent of Ekstra Bladet in DK) https://huggingface.co/datasets/Schibsted/vg-front-title 
- Seo or "google titles" from Svenska Dagbladet https://huggingface.co/datasets/Schibsted/svd-seo-title 

Personally I think the article summaries as most relevant for ScandEval 🙂

**Comment by saattrupdan** [comment]
We already added the Schibsted summaries in [v13.1.0](https://github.com/ScandEval/ScandEval/releases/tag/v13.1.0), and there is [another issue open regarding the other Schibsted tasks](https://github.com/ScandEval/ScandEval/issues/540), so closing this one. Appreciate it though!
