### ISSUE TITLE
[FEATURE REQUEST] ScandEval version on leaderboard

### ISSUE THREAD

**Issue by Mikeriess** [ScandEval/ScandEval#642]
### 🚀 The feature, motivation and pitch

As ScandEval evolves over time, a benchmark might need to be re-run to get an apples-to-apples comparison between the models. An example is https://github.com/ScandEval/ScandEval/releases/tag/v14.0.0 where the selection of chat template is changed. Even though a model might stay on the leaderboard with an "old" benchmark procedure, it would be good to be able to discern the difference between the procedure (e.g. by sorting on ScandEval version). 

### Alternatives

Adding the ScandEval version as a column to the leaderboard.

**Comment by saattrupdan** [comment]
It is already on the leaderboard, and I'm frequently that to prompt re-evaluations as well 🙂

I'm currently re-benchmarking all top ~10 generative models on all leaderboards to ensure consistency. Luckily, most of them seem to have the same performance. I currently don't have the hardware to benchmark the larger >8B models however.

**Comment by Mikeriess** [comment]
Hey @saattrupdan 😄 Sorry, I must be a little challenged but I dont see it in the Norwegian NLG leaderboard? 🤔 I see dataset versions, but not ScandEval version?

**Comment by Mikeriess** [comment]
Got it, apologies 😅
